### ISSUE TITLE
Add eslint-plugin-vue

### ISSUE THREAD

**Issue by joe-sharp** [nvuillam/mega-linter#152]
**Is your feature request related to a problem? Please describe.**
I have to disable the Vue.js plugin for eslint to be able to use mega-linter.

**Describe the solution you'd like**
It would be great if the plugin were supported.

**Describe alternatives you've considered**
A separate action to lint my .vue files.

**Additional context**
There is of course a chance this is user error, however this page suggests it isn't supported yet: https://github.com/nvuillam/mega-linter/blob/master/docs/descriptors/javascript_eslint.md#installation-on-mega-linter-docker-image

**Comment by nvuillam** [comment]
I'm on it :) 
I have never used Vue.js , are there .vue files , or is it just .js ? I need the file extensions to know how to implement ^^

For examples, for react there are .jsx and .tsx

**Comment by joe-sharp** [comment]
There are .vue files. They contain html, javascript, and scss all in the one file typically. Here is a link to an open PR on super-linter in the hopes it helps!

https://github.com/github/super-linter/pull/673

**Comment by joe-sharp** [comment]
Here is the full docs from Vue.js on single file components:

https://vuejs.org/v2/guide/single-file-components.html

**Comment by nvuillam** [comment]
Thanks for the info, it seems quite doable, CI will tell if my attempt is ok 👍 
I could just add the npm plugin + .vue file extension, but i'd prefer to also have working test cases for .vue files... please keep a look here, I'll probably ask you to test with @insiders version on your project,  before the enhancement goes to the next stable release :)

**Comment by joe-sharp** [comment]
Sounds good. Yeah I got about as far as your initial PR myself on the fork I made, but I saw you were including tests for everything. I saw your comments here before I got further. I would be happy to do a test run on my project. I am currently getting the rest of that project playing nicely with the rest of mega-linter! Thanks for you work and quick replies on this!!

**Comment by nvuillam** [comment]
I struggle to put tests, because javascript test folder contains a .eslintrc.json for all tests,, and the existing one is not related to Vue files ...

When [this run](https://github.com/nvuillam/mega-linter/runs/1543654329?check_suite_focus=true) is completed (probably 15 mn because CI rebuilds all the docker image) , you'll be able to test with **nvuillam/mega-linter@alpha** action / docker image in your project, with a Vue-flavored .eslintrc.js config file :)
If it works, i'll merge my PR, anyway it can't break other linters anyway so the risk is close to none

Thanks for the thanks, if you like the tool , you can [star it](https://github.com/nvuillam/mega-linter/stargazers) and/or post its [link](https://nvuillam.github.io/mega-linter/) anywhere you think it can help people ^^

**Comment by nvuillam** [comment]
@joe-sharp , **nvuillam/mega-linter@alpha** is ready for your test :)

**Comment by joe-sharp** [comment]
> @joe-sharp , **nvuillam/mega-linter@alpha** is ready for your test :)

On it!

**Comment by joe-sharp** [comment]
Running: https://github.com/joe-sharp/treehouse-vue/pull/7/checks?check_run_id=1543724379

**Comment by nvuillam** [comment]
![image](https://user-images.githubusercontent.com/17500430/101996487-2dda9d80-3cd3-11eb-887a-a72a8a5c1d6a.png)
You should put these ones at the root of the repo, so mega-linter is not the only one to see them, but also your local IDE and its plugins :)

**Comment by nvuillam** [comment]
I see lots of style errors
![image](https://user-images.githubusercontent.com/17500430/101996557-d4bf3980-3cd3-11eb-9f58-dbe9e0b620c2.png)

I'm sure that if you uncomment APPLY_FIXES in mega-linter.yml, you'll have less errors :) ( and in artifacts you'll have fixed sources )

But in my opinion, eslint-plugin-vue seems to work, right ?

**Comment by joe-sharp** [comment]
Thanks for the tip! I will definitely consider this, I might make a submodule for all these and have my editors look for this directory just to keep things simple. So does mega-lint look in project root by default? I know I had issues with that on super-lint. (Which I couldn't get to work with rubocop at all.)

Definitely going to uncomment APPLY_FIXES once I have my config files all set up and being read.

YES the plugin is working magnificently!! Thanks you so much, I had a lot of fun today! 😃

**Comment by nvuillam** [comment]
Ok so I merge the PR :) 
Usually, linter config files are located at the root of the repos
On each linter documentation on mega-linter doc, you'll see a section IDES , and if you install related plugins, they'll look by default to the same files than mega-linter are using, so that way you don't have to configure path on mega-linter or on IDEs

Ex: https://nvuillam.github.io/mega-linter/descriptors/html_htmlhint/#ide-integration

.htmlintrc will be used by mega-linter but also by [htmlhint vs code plugin](https://marketplace.visualstudio.com/items?itemName=mkaufman.HTMLHint)
