### ISSUE TITLE
Add support of `safety` for python

### ISSUE THREAD

**Issue by asiekkowa** [nvuillam/mega-linter#504]
Add support of running safety check: https://pypi.org/project/safety/

**Comment by nvuillam** [comment]
not stale

**Comment by tpansino** [comment]
@nvuillam I was thinking about trying to add this, but since you don't have other dependency-check linters in the tool, I was wondering if it would be better to use a more language-agnostic tool, like [snyk](https://github.com/snyk/snyk) or something.

Otherwise, `safety` is decent, but specific to Python.
