### ISSUE TITLE
Is it possible to allow real-time feedback in IDEs using Mega Linter?

### ISSUE THREAD

**Issue by TropicalRaisel** [nvuillam/mega-linter#671]
I believe a project like this is necessary in the current development ecosystem. Just in testing this I've been able to delete over eight different linter configuration files and many project dependencies.

The biggest wall for this project IMO is IDE integration. One of the benefits to an environment like VSCode and its many linter extensions is that you can get real-time feedback when things are wrong. I get that the primary focus in the project is to optimize CI linting, but it *could* handle any linting desire. Having an option like `EXPORT_ENABLED_CONFIGS` at least would be nice to leverage the plugins and such that already exist.

It would be a good idea to have only one Docker container be used over the program's lifetime. I've noticed that a new container is created each time it's run. At least having an option like `NEW_DOCKER_CONTAINER: true/false` would be nice.

**Comment by nvuillam** [comment]
Sorry for the reply delay, I had to think about it... :)

Mega-Linter being based on a docker image, it would be too system resources consuming to run it everytime we update a file in an IDE. In addition, each linter having its own output format, it would be almost impossible to highlight the lines in error in files, provide QuickFixes, etc...

But Mega-Linter contain : 
- default linter configuration files
- links to the linters related IDE extensions (and those ones are made for instant IDE notification)

So in order to ease the use of these linter configs and installation on related IDE extensions, Mega-Linter could provide in reports
- The list of links to click to install related linter IDE extensions
- a folder containing the linter config files to copy-paste at the root of the repo (and maybe an option to create a new commit with such updates, if we are running in Github actions for example)

So.... not exactly what you're asking, but it would cover in a different way the requirement you describe, what do you think ?

**Comment by TropicalRaisel** [comment]
Yes, having a way to at least access the config files used by the program will encourage live static code analysis and the CI configuration from this program.
