### ISSUE TITLE
Issues with secretlint

### ISSUE THREAD

**Issue by Esya** [nvuillam/mega-linter#684]
Two issues with secretlint in mega-linter : 

1- Secretlint always scans the whole repository from root - even when running with `VALIDATE_ALL_CODEBASE` set to false
2- Secretlint seems to completely ignore `CREDENTIALS_SECRETLINT_FILTER_REGEX_EXCLUDE` - and since they do not provide an easy way to exclude files or folders in their [configuration](https://github.com/secretlint/secretlint#configuration) the only fix is to turn it off for now

**Comment by nvuillam** [comment]
@Esya > Some linters run on the whole project and not on a list of files, in order to have better performances for Mega-Linter

The downside is that for those linters, VALIDATE_ALL_CODEBASE , FILTER_REGEX_INCLUDE and FILTER_REGEX_EXCLUDE are not always taken in account

So, you can:
- disable CREDENTIALS_SECRETLINT using [DISABLE_LINTERS property in .mega-linter.yml config file](https://nvuillam.github.io/mega-linter/configuration/#activation-and-deactivation)
- define a `.secretlintignore` file (same format that .gitignore, cf [example](https://github.com/secretlint/secretlint/blob/master/.secretlintignore))

On my side, I should disable such variables when the linters is not used with a list of files, I'll keep this issue open until I do
