### ISSUE TITLE
Report in JSON 

### ISSUE THREAD

**Issue by lokk3d** [nvuillam/mega-linter#694]
Hi! I'm currently working on Mega-Linter and is a really useful tool! 

I need to make data analysis on the report, so my goal is to get the report in json format. For now, I have created a function for the mega-linter.log that converts the summary in json. 

Is possible to create a JSON report of all other files in mega-linter? If not, will this feature be implemented in the future? 

This is my function: 
`   
const getTotalErrors = reportDir => {
    const filename = "mega-linter.log"
    const data = fs.readFileSync(path.join(reportDir, filename), { encoding: 'utf8' })
    const summarySeparator = "+----SUMMARY-----+"
    const errorArray = data.split(summarySeparator)[1].split("\n").splice(3)
    const errors = []

    for (let i = 0; i < errorArray.length; i++) {
        if (errorArray[i][0] === "+") break
        const data = errorArray[i].split("|").map(item => item.trim())

        errors.push({
            language: data[1].substring(2),
            errors: data[5]
        })
    }

    return errors
}

`

**Comment by nvuillam** [comment]
Instead of parsing the text report, maybe you'd like to directly have a JSON file as artefact, or maybe directly in the console log ?

What is your use case ?

Mega-Linter architecture allows to define additional reporters, so we could create a JSON one easily (instead of generating an ASCIITable we could generate a JSON [here](https://github.com/nvuillam/mega-linter/blob/09a3ab545301383bdbbb06599b52283ab74a183e/megalinter/reporters/ConsoleReporter.py#L55) for example )

But I have to know more about what you want to do with this JSON to help you :)

About having all linters generate their output in a single format... that will be possible the day all linters will be able to use a common format like SARIF, or if we find a way to parse errors, maybe with a tool like [errroformat](https://github.com/reviewdog/errorformat)

**Comment by lokk3d** [comment]
My use case is this one: 
i need to analyze multiple github repos (with obviously multiple programming languages).
I clone the repo, then I analyze it with Mega-Linter.
After this i need to parse in some way all the errors and save them into a MongoDb document.

It would be fantastic if we could find a way to uniform all the linters outputs to a common specific but i think this could be really tedious and difficulty

**Comment by nvuillam** [comment]
How do you call Mega-Linter ?
mega-linter-runner ? docker run ? Or with another CI job ?

**Comment by lokk3d** [comment]
mega-linter-runner

**Comment by nvuillam** [comment]
Great :)
Would the following proposal fit your needs ?

- have a `--json` option to mega-linter-runner
- that would make return as stdout a json string containing [results information](https://nvuillam.github.io/mega-linter/assets/images/ConsoleReporter.jpg)

Basically, I would update the console reporter so instead of generating "human readable" results, it would generate exploitable json

**Comment by lokk3d** [comment]
it would be great!

**Comment by nvuillam** [comment]
I agree :)
I add that to my to-do list , should be ok in a few days ^^

**Comment by lokk3d** [comment]
Great! Really thanks for your help, really appreciated!

**Comment by lokk3d** [comment]
1.

**Comment by nvuillam** [comment]
Let's keep the issue open until it's done ;)

**Comment by nvuillam** [comment]
I have a first version working and published in insiders/latest version, but I'll enhance it to add a "less chatty" mode :)

**Comment by nvuillam** [comment]
@lokk3d the function is ready in insiders/latest version :) 

default mode (simple) contains a subset of all execution and should be ok for your requirements

If this is not enough, detailed mode provides about about everything that happened during the run, including configuration data :)

please let me know that it's all ok for you ^^

https://nvuillam.github.io/mega-linter/reporters/JsonReporter/

**Comment by lokk3d** [comment]
@nvuillam Right now it is not working for me. I'm using mega-linter-runner version 4.41.0 and I'm using this command: mega-linter-runner -e 'JSON_REPORTER=true' after updating mega-linter-runner I'm getting also the 4.41.0 version. How to use the updated version?

**Comment by nvuillam** [comment]
- If you want JSON output in console AND mega-linter-report.json

`npx mega-linter-runner@beta --version --release latest -e 'JSON_REPORTER=true'` 

or

`npx mega-linter-runner@beta --version --release latest`
JSON_REPORTER:true in your .mega-linter.yml

- If you just want the file in /report/mega-linter-report.json

`npx mega-linter-runner@beta --version --release latest --json`
